"""Remove donation and alert fields from user model

Revision ID: 02c2730351c6
Revises: b1cf14726d07
Create Date: 2025-07-16 22:40:36.479183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c2730351c6'
down_revision = 'b1cf14726d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_key')
        batch_op.drop_column('donation_count')
        batch_op.drop_column('total_donations')
        batch_op.drop_column('donation_goal')
        batch_op.drop_column('alert_message_template')
        batch_op.drop_column('webhook_url')
        batch_op.drop_column('min_alert_amount')
        batch_op.drop_column('alert_sound_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_sound_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('min_alert_amount', sa.NUMERIC(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('webhook_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('alert_message_template', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('donation_goal', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_donations', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('donation_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
