"""Add progress animation setting

Revision ID: 1055da1b391b
Revises: ba6a6a40ecea
Create Date: 2025-07-18 16:51:20.912470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1055da1b391b'
down_revision = 'ba6a6a40ecea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_animation', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_goals', schema=None) as batch_op:
        batch_op.drop_column('progress_animation')

    # ### end Alembic commands ###
