"""Create marathon table

Revision ID: 19ea2fe56603
Revises: 1055da1b391b
Create Date: 2025-07-18 17:52:00.843802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ea2fe56603'
down_revision = '1055da1b391b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marathons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('minute_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('initial_time_minutes', sa.Integer(), nullable=False),
    sa.Column('remaining_time_minutes', sa.Integer(), nullable=False),
    sa.Column('donated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('manual_adjustments_minutes', sa.Integer(), nullable=False),
    sa.Column('timer_font_size', sa.Integer(), nullable=False),
    sa.Column('timer_font_weight', sa.Integer(), nullable=False),
    sa.Column('timer_font_color', sa.String(length=7), nullable=False),
    sa.Column('notification_font_size', sa.Integer(), nullable=False),
    sa.Column('notification_font_weight', sa.Integer(), nullable=False),
    sa.Column('notification_font_color', sa.String(length=7), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('total_paused_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marathons')
    # ### end Alembic commands ###
