"""Add accumulated_donations field to marathon table

Revision ID: 27cfe23a8418
Revises: 5b3d2f7883a1
Create Date: 2025-07-18 22:15:20.754577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cfe23a8418'
down_revision = '5b3d2f7883a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accumulated_donations', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.drop_column('accumulated_donations')

    # ### end Alembic commands ###
