"""Add platform connections for multi-platform OAuth

Revision ID: 29d60cbf4af4
Revises: 02c2730351c6
Create Date: 2025-07-16 22:55:37.602542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d60cbf4af4'
down_revision = '02c2730351c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_type', sa.Enum('TWITCH', 'YOUTUBE', 'KICK', name='platformtype'), nullable=False),
    sa.Column('platform_user_id', sa.String(length=100), nullable=False),
    sa.Column('platform_username', sa.String(length=100), nullable=False),
    sa.Column('platform_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('platform_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_type', name='_user_platform_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_connections')
    # ### end Alembic commands ###
