"""Add metadata_json field to subscription payments for tier change tracking

Revision ID: 491fe34057bb
Revises: 952c78a795dc
Create Date: 2025-07-22 00:30:41.492475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491fe34057bb'
down_revision = '952c78a795dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_payments', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    # ### end Alembic commands ###
