"""Add timer_animation field to marathon table

Revision ID: 5b3d2f7883a1
Revises: 9bc40efa24ae
Create Date: 2025-07-18 20:29:03.871857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3d2f7883a1'
down_revision = '9bc40efa24ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_animation', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.drop_column('timer_animation')

    # ### end Alembic commands ###
