"""Add is_primary field to platform_connections

Revision ID: 5ffe65548e5a
Revises: 29d60cbf4af4
Create Date: 2025-07-17 14:44:27.731234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffe65548e5a'
down_revision = '29d60cbf4af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_connections', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
