"""Add remaining_time_seconds field to marathon table

Revision ID: 640118d682e0
Revises: 19ea2fe56603
Create Date: 2025-07-18 19:53:00.330846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640118d682e0'
down_revision = '19ea2fe56603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_time_seconds', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.drop_column('remaining_time_seconds')

    # ### end Alembic commands ###
