"""Add tts_pitch field to donation_alert_settings

Revision ID: 660925e68b26
Revises: cb546d4fda40
Create Date: 2025-07-18 00:14:11.128409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660925e68b26'
down_revision = 'cb546d4fda40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_alert_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tts_pitch', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_alert_settings', schema=None) as batch_op:
        batch_op.drop_column('tts_pitch')

    # ### end Alembic commands ###
