"""Add subscription payment model and user bank account fields

Revision ID: 68365d9c6ec7
Revises: a98c2eac9ee7
Create Date: 2025-07-17 15:22:03.742519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68365d9c6ec7'
down_revision = 'a98c2eac9ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quickpay_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('quickpay_merchant_id', sa.String(length=100), nullable=True),
    sa.Column('quickpay_terminal_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('webhook_token', sa.String(length=100), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('callback_data', sa.Text(), nullable=True),
    sa.Column('qr_code_text', sa.Text(), nullable=True),
    sa.Column('qr_image_base64', sa.Text(), nullable=True),
    sa.Column('app_links', sa.Text(), nullable=True),
    sa.Column('payment_url', sa.String(length=500), nullable=True),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference'),
    sa.UniqueConstraint('quickpay_invoice_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_iban', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('bank_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_bank_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_bank_verified')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_code')
        batch_op.drop_column('bank_iban')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_account_name')

    op.drop_table('subscription_payments')
    # ### end Alembic commands ###
