"""Add volume control to user sound settings

Revision ID: 77b6bceb5278
Revises: 863d451b92d3
Create Date: 2025-07-21 18:17:04.439488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b6bceb5278'
down_revision = '863d451b92d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sound_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sound_settings', schema=None) as batch_op:
        batch_op.drop_column('volume_level')

    # ### end Alembic commands ###
