"""Add message_style field to donation alert settings

Revision ID: 84ad1c6972c6
Revises: efa86e15ebb9
Create Date: 2025-07-17 21:39:11.424653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ad1c6972c6'
down_revision = 'efa86e15ebb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_alert_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_style', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_alert_settings', schema=None) as batch_op:
        batch_op.drop_column('message_style')

    # ### end Alembic commands ###
