"""Add sound effects feature tables and columns

Revision ID: 863d451b92d3
Revises: 99eeea8af775
Create Date: 2025-07-20 23:34:08.409752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863d451b92d3'
down_revision = '99eeea8af775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('sound_effects', schema=None) as batch_op:
        batch_op.create_index('idx_active', ['is_active'], unique=False)
        batch_op.create_index('idx_category', ['category'], unique=False)

    op.create_table('user_sound_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('price_per_sound', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_sound_settings')
    )
    op.create_table('sound_effect_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sound_effect_id', sa.Integer(), nullable=False),
    sa.Column('streamer_user_id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(length=100), nullable=False),
    sa.Column('donor_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('donation_payment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donation_payment_id'], ['donation_payments.id'], ),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sound_effect_id'], ['sound_effects.id'], ),
    sa.ForeignKeyConstraint(['streamer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sound_effect_donations', schema=None) as batch_op:
        batch_op.create_index('idx_sound_effect', ['sound_effect_id'], unique=False)
        batch_op.create_index('idx_streamer_date', ['streamer_user_id', 'created_at'], unique=False)

    with op.batch_alter_table('donation_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('alert', 'sound_effect', name='payment_type'), nullable=True))
        batch_op.add_column(sa.Column('sound_effect_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sound_effects', ['sound_effect_id'], ['id'])

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('alert', 'sound_effect', name='donation_type'), nullable=True))
        batch_op.add_column(sa.Column('sound_effect_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sound_effects', ['sound_effect_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sound_effect_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('donation_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sound_effect_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('sound_effect_donations', schema=None) as batch_op:
        batch_op.drop_index('idx_streamer_date')
        batch_op.drop_index('idx_sound_effect')

    op.drop_table('sound_effect_donations')
    op.drop_table('user_sound_settings')
    with op.batch_alter_table('sound_effects', schema=None) as batch_op:
        batch_op.drop_index('idx_category')
        batch_op.drop_index('idx_active')

    op.drop_table('sound_effects')
    # ### end Alembic commands ###
