"""Add scheduled tier change fields to subscriptions

Revision ID: 952c78a795dc
Revises: e8c74d3f7d93
Create Date: 2025-07-22 00:21:46.936847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952c78a795dc'
down_revision = 'e8c74d3f7d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_tier_change', sa.Enum('BASIC', 'ADVANCED', name='subscriptiontier'), nullable=True))
        batch_op.add_column(sa.Column('scheduled_change_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_change_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('scheduled_change_months')
        batch_op.drop_column('scheduled_change_date')
        batch_op.drop_column('scheduled_tier_change')

    # ### end Alembic commands ###
