"""Add default asset name fields to alert configurations

Revision ID: 95a60029a756
Revises: cda4742537d6
Create Date: 2025-07-20 00:44:02.941217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a60029a756'
down_revision = 'cda4742537d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_gif_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_sound_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configurations', schema=None) as batch_op:
        batch_op.drop_column('default_sound_name')
        batch_op.drop_column('default_gif_name')

    # ### end Alembic commands ###
