"""Add dev_access column to users table

Revision ID: 99eeea8af775
Revises: aeae45e6a210
Create Date: 2025-07-20 22:17:42.387565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eeea8af775'
down_revision = 'aeae45e6a210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dev_access')

    # ### end Alembic commands ###
