"""Convert BASIC subscriptions to MONTHLY

Revision ID: 9a37f16d872a
Revises: 27cfe23a8418
Create Date: 2025-07-19 22:18:56.631262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a37f16d872a'
down_revision = '27cfe23a8418'
branch_labels = None
depends_on = None


def upgrade():
    # First, modify the enum to include all new values
    connection = op.get_bind()
    connection.execute(sa.text("ALTER TABLE subscriptions MODIFY tier ENUM('FREE_TRIAL','BASIC','MONTHLY','QUARTERLY','BIANNUAL','ANNUAL')"))
    
    # Data migration: Convert BASIC subscriptions to MONTHLY
    connection.execute(sa.text("UPDATE subscriptions SET tier = 'MONTHLY' WHERE tier = 'BASIC'"))
    
    # Remove BASIC from enum (optional - for cleaner schema)
    # connection.execute(sa.text("ALTER TABLE subscriptions MODIFY tier ENUM('FREE_TRIAL','MONTHLY','QUARTERLY','BIANNUAL','ANNUAL')"))
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_alert_settings', schema=None) as batch_op:
        batch_op.drop_column('threshold_amount')
        batch_op.drop_column('tier_order')
        batch_op.drop_column('tier_name')
        batch_op.drop_column('is_default')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('scheduled_downgrade_tier')
        batch_op.drop_column('duration_months')
        batch_op.drop_column('scheduled_downgrade_duration_months')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_downgrade_duration_months', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration_months', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('scheduled_downgrade_tier', mysql.ENUM('FREE_TRIAL', 'BASIC', 'ADVANCED'), nullable=True))

    with op.batch_alter_table('donation_alert_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tier_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('tier_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('threshold_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
