"""Add overlay_token field to marathon table for secure URLs

Revision ID: 9bc40efa24ae
Revises: 640118d682e0
Create Date: 2025-07-18 20:16:23.444454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc40efa24ae'
down_revision = '640118d682e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overlay_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['overlay_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('overlay_token')

    # ### end Alembic commands ###
