"""add donation payments table

Revision ID: a8e119df16d0
Revises: 0272defb6b22
Create Date: 2025-07-18 12:50:41.381048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e119df16d0'
down_revision = '0272defb6b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streamer_user_id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(length=100), nullable=False),
    sa.Column('donor_platform', sa.String(length=50), nullable=True),
    sa.Column('donor_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('quickpay_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('quickpay_merchant_id', sa.String(length=100), nullable=True),
    sa.Column('quickpay_terminal_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('qr_image', sa.Text(), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('app_links', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['streamer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quickpay_invoice_id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_payment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'donation_payments', ['donation_payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_test')
        batch_op.drop_column('donation_payment_id')

    op.drop_table('donation_payments')
    # ### end Alembic commands ###
