"""Create donor leaderboard tables

Revision ID: ada803320bbb
Revises: 77b6bceb5278
Create Date: 2025-07-21 19:46:47.788547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada803320bbb'
down_revision = '77b6bceb5278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('donor_name', sa.String(length=255), nullable=False),
    sa.Column('donor_user_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('donation_count', sa.Integer(), nullable=False),
    sa.Column('biggest_single_donation', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_donation_date', sa.DateTime(), nullable=False),
    sa.Column('first_donation_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'donor_name', name='unique_streamer_donor')
    )
    with op.batch_alter_table('donor_leaderboard', schema=None) as batch_op:
        batch_op.create_index('idx_donor_user', ['donor_user_id'], unique=False)
        batch_op.create_index('idx_leaderboard', ['user_id', 'total_amount'], unique=False)

    op.create_table('donor_leaderboard_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('positions_count', sa.Integer(), nullable=True),
    sa.Column('show_amounts', sa.Boolean(), nullable=True),
    sa.Column('show_donation_counts', sa.Boolean(), nullable=True),
    sa.Column('throne_styling', sa.Text(), nullable=True),
    sa.Column('podium_styling', sa.Text(), nullable=True),
    sa.Column('standard_styling', sa.Text(), nullable=True),
    sa.Column('global_styling', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_settings')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donor_leaderboard_settings')
    with op.batch_alter_table('donor_leaderboard', schema=None) as batch_op:
        batch_op.drop_index('idx_leaderboard')
        batch_op.drop_index('idx_donor_user')

    op.drop_table('donor_leaderboard')
    # ### end Alembic commands ###
