"""Add donation goal model

Revision ID: ba6a6a40ecea
Revises: a8e119df16d0
Create Date: 2025-07-18 16:07:41.711952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6a6a40ecea'
down_revision = 'a8e119df16d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('manual_adjustments', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('title_font_size', sa.Integer(), nullable=False),
    sa.Column('title_font_weight', sa.Integer(), nullable=False),
    sa.Column('title_color', sa.String(length=7), nullable=False),
    sa.Column('progress_height', sa.Integer(), nullable=False),
    sa.Column('progress_text_size', sa.Integer(), nullable=False),
    sa.Column('progress_font_weight', sa.Integer(), nullable=False),
    sa.Column('progress_font_color', sa.String(length=7), nullable=False),
    sa.Column('progress_color', sa.String(length=7), nullable=False),
    sa.Column('progress_background_color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation_goals')
    # ### end Alembic commands ###
