"""Add overlay_token field to User model for secure URLs

Revision ID: cb546d4fda40
Revises: 84ad1c6972c6
Create Date: 2025-07-17 21:45:11.746795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb546d4fda40'
down_revision = '84ad1c6972c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overlay_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_overlay_token'), ['overlay_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_overlay_token'))
        batch_op.drop_column('overlay_token')

    # ### end Alembic commands ###
