"""Add alert_configurations table for multi-tab alert system

Revision ID: cda4742537d6
Revises: bd738355bbe1
Create Date: 2025-07-20 00:32:16.853751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda4742537d6'
down_revision = 'bd738355bbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tab_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('text_template', sa.Text(), nullable=True),
    sa.Column('minimum_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('visible_time', sa.Integer(), nullable=True),
    sa.Column('animation_speed', sa.Integer(), nullable=True),
    sa.Column('transition_type', sa.String(length=50), nullable=True),
    sa.Column('image_position', sa.String(length=20), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('selected_gif_id', sa.Integer(), nullable=True),
    sa.Column('sound_volume', sa.Integer(), nullable=True),
    sa.Column('selected_sound_id', sa.Integer(), nullable=True),
    sa.Column('tts_enabled', sa.Boolean(), nullable=True),
    sa.Column('tts_minimum_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tts_speed', sa.Float(), nullable=True),
    sa.Column('tts_voice', sa.String(length=50), nullable=True),
    sa.Column('tts_pitch', sa.Float(), nullable=True),
    sa.Column('donator_image_size', sa.Integer(), nullable=True),
    sa.Column('donator_name_size', sa.Integer(), nullable=True),
    sa.Column('donator_name_weight', sa.String(length=20), nullable=True),
    sa.Column('donator_alignment', sa.String(length=20), nullable=True),
    sa.Column('donator_color', sa.String(length=7), nullable=True),
    sa.Column('template_size', sa.Integer(), nullable=True),
    sa.Column('template_weight', sa.String(length=20), nullable=True),
    sa.Column('template_alignment', sa.String(length=20), nullable=True),
    sa.Column('template_base_color', sa.String(length=7), nullable=True),
    sa.Column('template_accent_color', sa.String(length=7), nullable=True),
    sa.Column('message_size', sa.Integer(), nullable=True),
    sa.Column('message_weight', sa.String(length=20), nullable=True),
    sa.Column('message_style', sa.String(length=20), nullable=True),
    sa.Column('message_alignment', sa.String(length=20), nullable=True),
    sa.Column('message_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['selected_gif_id'], ['user_assets.id'], ),
    sa.ForeignKeyConstraint(['selected_sound_id'], ['user_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tab_number', name='unique_user_tab')
    )
    with op.batch_alter_table('alert_configurations', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_tab', ['user_id', 'tab_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configurations', schema=None) as batch_op:
        batch_op.drop_index('idx_user_tab')
        batch_op.drop_index('idx_user_active')

    op.drop_table('alert_configurations')
    # ### end Alembic commands ###
