"""Add overlay_token to donor leaderboard settings

Revision ID: e8c74d3f7d93
Revises: ada803320bbb
Create Date: 2025-07-21 20:10:53.072384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c74d3f7d93'
down_revision = 'ada803320bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_leaderboard_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overlay_token', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['overlay_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_leaderboard_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('overlay_token')

    # ### end Alembic commands ###
