"""Add donation alert settings and user assets tables

Revision ID: efa86e15ebb9
Revises: 68365d9c6ec7
Create Date: 2025-07-17 19:33:16.315707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa86e15ebb9'
down_revision = '68365d9c6ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donation_alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_template', sa.Text(), nullable=True),
    sa.Column('minimum_amount', sa.Integer(), nullable=True),
    sa.Column('visible_time', sa.Integer(), nullable=True),
    sa.Column('animation_speed', sa.Integer(), nullable=True),
    sa.Column('transition_type', sa.String(length=50), nullable=True),
    sa.Column('tts_enabled', sa.Boolean(), nullable=True),
    sa.Column('tts_minimum_amount', sa.Integer(), nullable=True),
    sa.Column('tts_voice', sa.String(length=50), nullable=True),
    sa.Column('tts_speed', sa.Float(), nullable=True),
    sa.Column('image_position', sa.String(length=20), nullable=True),
    sa.Column('selected_gif_id', sa.Integer(), nullable=True),
    sa.Column('default_gif_name', sa.String(length=100), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('selected_sound_id', sa.Integer(), nullable=True),
    sa.Column('default_sound_name', sa.String(length=100), nullable=True),
    sa.Column('sound_volume', sa.Integer(), nullable=True),
    sa.Column('donator_image_size', sa.Integer(), nullable=True),
    sa.Column('donator_name_size', sa.Integer(), nullable=True),
    sa.Column('donator_name_weight', sa.String(length=20), nullable=True),
    sa.Column('donator_alignment', sa.String(length=20), nullable=True),
    sa.Column('donator_color', sa.String(length=7), nullable=True),
    sa.Column('template_size', sa.Integer(), nullable=True),
    sa.Column('template_weight', sa.String(length=20), nullable=True),
    sa.Column('template_alignment', sa.String(length=20), nullable=True),
    sa.Column('template_accent_color', sa.String(length=7), nullable=True),
    sa.Column('template_base_color', sa.String(length=7), nullable=True),
    sa.Column('message_size', sa.Integer(), nullable=True),
    sa.Column('message_weight', sa.String(length=20), nullable=True),
    sa.Column('message_alignment', sa.String(length=20), nullable=True),
    sa.Column('message_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['selected_gif_id'], ['user_assets.id'], ),
    sa.ForeignKeyConstraint(['selected_sound_id'], ['user_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation_alert_settings')
    op.drop_table('user_assets')
    # ### end Alembic commands ###
